version: 2

jobs:
  build:
    working_directory: ~/amset
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Make tox env and run tests
          command: |
            mkdir ~/tox_env
            python -m venv ~/tox_env
            source ~/tox_env/bin/activate
            pip install --upgrade pip
            pip install tox tox-pyenv
            pip install --quiet numpy cython cmake
            pip install --quiet -r requirements.txt
            pip install --quiet -r requirements-optional.txt
            tox
          no_output_timeout: 90m