version: 2

jobs:
  build:
    working_directory: ~/amset
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: env and run tests
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            sudo apt-get update
            sudo apt-get install build-essential
            sudo apt-get install gcc g++
            pip install --upgrade pip
            pip install --quiet numpy cmake
            pip install --quiet -r requirements.txt
            pip install -r requirements-optional.txt
            python setup.py test
          no_output_timeout: 60m