version: 2

jobs:
  build:
    working_directory: ~/amset
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: env and run tests
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            pip install --upgrade pip
            pip install --quiet numpy cython cmake
            pip install --quiet -r requirements.txt
            CFLAGS="-std=c++11 -stdlib=libc++"
            pip install -r requirements-optional.txt
            python setup.py test
          no_output_timeout: 60m