version: 2

jobs:
  build:
    working_directory: ~/amset
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Make tox env
          command: |
            mkdir ~/tox_env
            python -m venv ~/tox_env
            source ~/tox_env/bin/activate
            pip install --upgrade pip
            pip install tox tox-pyenv
            pip install numpy
            pip install -r requirements.txt -r requirements-optional.txt
      - run:
          name: Run amset tests
          command: |
            source ~/tox_env/bin/activate
            tox
          no_output_timeout: 90m