version: 2

jobs:
  build:
    working_directory: ~/amset
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: dependencies in py3 env gcc g++ for boltztrap2 and run tests
          command: |
            sudo apt-get install gcc
            sudo apt-get install g++
            export CC=/usr/bin/gcc
            export CXX=/usr/bin/g++
            export CFLAGS="-std=c++11"
            python3 -m venv test_env
            . test_env/bin/activate
            pip install --upgrade pip
            pip install --quiet numpy cython cmake
            pip install --quiet -r requirements.txt
            pip install --quiet -r requirements-optional.txt
            python setup.py test
          no_output_timeout: 120m