# This is an example amset settings file.
general:

    # band gap settings
    scissor: null                     # in eV
    bandgap: 3.0                 # in eV

    # options include ACD, PIE, IMP, DIS, and POP. E.g.:
    # scattering_type: ACD, POP, IMP
    # alternatively, set to auto to automatically determine
    # scattering_type based on material parameters
    # could allow "inv_dos" or "CRTA" + rate. E.g.:
    # scattering_type: inv_dos 1E-14
    scattering_type: auto

    interpolation_factor: 10

    doping: 1e15, 1e16, 1e17, 1e18, 1e19, 1e20, 1e21
    temperatures: 300

material:
    # dielectric constants
    high_frequency_dielectric: 3
    static_dielectric: 6

    # ACD parameters
    elastic_constant: 150             # in GPa
    deformation_potential_vbm: 9      # in eV
    deformation_potential_cbm: 9      # in eV

    # PIE parameters
    piezeoelectric_coefficient: 0.15  # in ?

    # IMP parameters
    acceptor_charge: 1
    donor_charge: 1

    # POP parameters
    pop_frequency: 10                 # in ?

    # DIS parameters
    n_dislocations: 0.1
    dislocation_charge: 1

performance:
    energy_tol: 0.0001                # in eV
    energy_cutoff: 1.5                # in eV
    g_tol: 1                          # in %
    dos_estep: 0.01                   # in eV
    dos_width: 0.01                   # in eV
    symprec: 0.01                     # in Angstrom
    nworkers: -1
