general:
    doping: [1.99e+14, 2.20e+15, 1.72e+16, 1.86e+17, 1.46e+18, 4.39e+18]
    temperatures: [300]
    interpolation_factor: 50
    scattering_type: auto

material:
    deformation_potential: [6.5, 6.5]
    acceptor_charge: 1
    donor_charge: 1
    elastic_constant: 190
    pop_frequency: 15.23
    static_dielectric: 13.1
    high_frequency_dielectric: 13.1

output:
    calculate_mobility: true
    file_format: json

performance:
    dos_estep: 0.01
    energy_cutoff: 1.5
    symprec: 0.01
    energy_tol: 0.001
    nworkers: -1
